### PR TITLE
update contributor instructions

### PR DESCRIPTION
**Pull request by imavroukakis**

### CODE REVIEW

**Review by beevee — CHANGES_REQUESTED** [review]
Can you please update these instructions to reflect the fact that we now use Go modules instead of govendor?

**Comment by imavroukakis** [comment]
@beevee done, is this ok?

**Comment by beevee** [comment]
One of the most noticeable advantages of Go modules is that you don't need `GOPATH` anymore. You can check out your code in any folder. So, I think, you'll have to recheck which steps are no longer necessary.

**Comment by imavroukakis** [comment]
Won't you need to pull `goconvey` into the GOPATH though so you can execute it?

**Review by beevee — APPROVED** [review]

**Pull request merged**
